name: "Get Secrets"
description: "Fetch secrets from OpenBao and expose them as environment variables"

inputs:
  url:
    description: "Base URL of the bao instance"
    required: true
  token:
    description: "Token used to authenticate"
    required: true
  mount:
    description: "Name of the KV mount in the bao instance"
    required: true
  secrets:
    description: |
      JSON object mapping secret paths to keys inside those secrets.
      Example:
      {
        "path/to/secret1": ["some_key", "other_key"],
        "path/to/secret2": "another_key"
      }
    required: true

runs:
  using: "composite"
  steps:
    - name: Install jq
      shell: bash
      run: |
        if ! command -v jq >/dev/null 2>&1; then
          sudo apt-get update -y
          sudo apt-get install -y jq
        fi

    - name: Fetch secrets
      shell: bash
      env:
        OPENBAO_URL: ${{ inputs.url }}
        OPENBAO_TOKEN: ${{ inputs.token }}
        OPENBAO_MOUNT: ${{ inputs.mount }}
        OPENBAO_SECRETS: ${{ inputs.secrets }}
      run: |
        set -euo pipefail

        echo "Fetching secrets from OpenBao at $OPENBAO_URL..."

        if [ -z "${OPENBAO_SECRETS:-}" ]; then
          echo "Error: 'secrets' input is empty" >&2
          exit 1
        fi

        # Validate that OPENBAO_SECRETS is an object
        if ! echo "$OPENBAO_SECRETS" | jq -e 'type == "object"' >/dev/null 2>&1; then
          echo "Error: 'secrets' input must be a JSON object" >&2
          exit 1
        fi

        echo "$OPENBAO_SECRETS" \
        | jq -r '
            to_entries[]
            | .key as $path
            | .value
            | if type == "string" then [.] else . end
            | .[]
            | "\($path)\t\(.)"
          ' \
        | while IFS=$'\t' read -r raw_path raw_key; do
            path="${raw_path#"${raw_path%%[![:space:]]*}"}"
            path="${path%"${path##*[![:space:]]}"}"
            key="${raw_key#"${raw_key%%[![:space:]]*}"}"
            key="${key%"${key##*[![:space:]]}"}"

            if [ -z "$path" ] || [ -z "$key" ]; then
              echo "Warning: skipping entry with empty path or key" >&2
              continue
            fi

            api_url="$OPENBAO_URL/v1/$OPENBAO_MOUNT/data/$path"

            if ! json=$(curl -sS -f \
              -H "X-OpenBao-Token: $OPENBAO_TOKEN" \
              "$api_url"); then
              echo "Warning: failed to fetch secret at path '$path' (skipping)" >&2
              continue
            fi

            value=$(echo "$json" | jq -r --arg k "$key" '.data.data[$k] // empty')

            if [ -z "$value" ] || [ "$value" = "null" ]; then
              echo "Warning: no value found for key '$key' in secret path '$path' (skipping)" >&2
              continue
            fi

            env_name=$(printf "%s_%s" "$path" "$key" \
              | tr '[:lower:]' '[:upper:]' \
              | sed -E 's/[^A-Z0-9]+/_/g' \
              | sed -E 's/^_+//; s/_+$//')

            if [ -z "$env_name" ]; then
              echo "Warning: could not derive env var name from '$path' and '$key' (skipping)" >&2
              continue
            fi

            echo "Exporting secret '$path'[$key] as env var '$env_name'"

            {
              echo "${env_name}<<EOF"
              echo "$value"
              echo "EOF"
            } >> "$GITHUB_ENV"
          done
 
